-file("c:/Program Files/Erlang OTP/lib/parsetools-2.4/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(beehive_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("./beehive_lexer.xrl", 75).


-file("c:/Program Files/Erlang OTP/lib/parsetools-2.4/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transition state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("./beehive_lexer.erl", 308).
yystate() -> 88.

yystate(91, [101|Ics], Line, Tlen, _, _) ->
    yystate(89, Ics, Line, Tlen+1, 17, Tlen);
yystate(91, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(91, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,91};
yystate(90, [32|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 55, Tlen);
yystate(90, [13|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 55, Tlen);
yystate(90, [9|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 55, Tlen);
yystate(90, [10|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line+1, Tlen+1, 55, Tlen);
yystate(90, Ics, Line, Tlen, _, _) ->
    {55,Tlen,Ics,Line,90};
yystate(89, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 10, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 10, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 10, Tlen);
yystate(89, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,89};
yystate(88, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [64|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [36|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(82, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(90, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(90, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(90, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(90, Ics, Line+1, Tlen+1, Action, Alen);
yystate(88, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [C|Ics], Line, Tlen, Action, Alen) when C >= 98, C =< 100 ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [C|Ics], Line, Tlen, Action, Alen) when C >= 106, C =< 108 ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [C|Ics], Line, Tlen, Action, Alen) when C >= 113, C =< 115 ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [C|Ics], Line, Tlen, Action, Alen) when C >= 117, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(88, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,88};
yystate(87, [115|Ics], Line, Tlen, _, _) ->
    yystate(91, Ics, Line, Tlen+1, 17, Tlen);
yystate(87, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(87, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,87};
yystate(86, Ics, Line, Tlen, _, _) ->
    {50,Tlen,Ics,Line};
yystate(85, [110|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 17, Tlen);
yystate(85, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(85, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,85};
yystate(84, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(84, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,84};
yystate(83, [108|Ics], Line, Tlen, _, _) ->
    yystate(87, Ics, Line, Tlen+1, 17, Tlen);
yystate(83, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(83, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,83};
yystate(82, [61|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 30, Tlen);
yystate(82, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line,82};
yystate(81, [100|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 17, Tlen);
yystate(81, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(81, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,81};
yystate(80, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(80, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,80};
yystate(79, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 4, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 4, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 4, Tlen);
yystate(79, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,79};
yystate(78, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(77, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 1, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 1, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 1, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,77};
yystate(76, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line};
yystate(75, [101|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 17, Tlen);
yystate(75, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,75};
yystate(74, [123|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 32, Tlen);
yystate(74, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line,74};
yystate(73, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line};
yystate(72, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line};
yystate(71, [115|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 17, Tlen);
yystate(71, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(71, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,71};
yystate(70, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line};
yystate(69, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(68, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(67, [108|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 17, Tlen);
yystate(67, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(67, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,67};
yystate(66, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line};
yystate(65, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(64, [126|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 29, Tlen);
yystate(64, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 29, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,64};
yystate(63, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 6, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 6, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 6, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,63};
yystate(62, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line};
yystate(61, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(61, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,61};
yystate(60, [126|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 25, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line,60};
yystate(59, [110|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [97|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 109 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,59};
yystate(58, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(57, [95|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 18, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(57, Ics, Line, Tlen+1, 18, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(57, Ics, Line, Tlen+1, 18, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,57};
yystate(56, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line};
yystate(55, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 8, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 8, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 8, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,55};
yystate(54, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(54, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,54};
yystate(53, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line};
yystate(52, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(52, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,52};
yystate(51, [102|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,51};
yystate(50, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(50, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,50};
yystate(49, [61|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 53, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {53,Tlen,Ics,Line,49};
yystate(48, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line};
yystate(47, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 11, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 11, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 11, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,47};
yystate(46, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(45, Ics, Line, Tlen, _, _) ->
    {51,Tlen,Ics,Line};
yystate(44, [114|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 17, Tlen);
yystate(44, [112|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(44, [113|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(44, [111|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 17, Tlen);
yystate(44, [104|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 17, Tlen);
yystate(44, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 110 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,44};
yystate(43, [104|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 17, Tlen);
yystate(43, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,43};
yystate(42, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line};
yystate(41, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(41, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,41};
yystate(40, [117|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 17, Tlen);
yystate(40, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,40};
yystate(39, [99|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 17, Tlen);
yystate(39, [97|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(39, [98|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(39, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,39};
yystate(38, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line};
yystate(37, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line};
yystate(36, [101|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,36};
yystate(35, [116|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 17, Tlen);
yystate(35, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,35};
yystate(34, [46|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 39, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(2, Ics, Line, Tlen+1, 39, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {39,Tlen,Ics,Line,34};
yystate(33, Ics, Line, Tlen, _, _) ->
    {49,Tlen,Ics,Line};
yystate(32, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 3, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 3, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 3, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,32};
yystate(31, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 5, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 5, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 5, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,31};
yystate(30, Ics, Line, Tlen, _, _) ->
    {43,Tlen,Ics,Line};
yystate(29, [61|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 54, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {54,Tlen,Ics,Line,29};
yystate(28, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 12, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 12, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 12, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,28};
yystate(27, [100|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 17, Tlen);
yystate(27, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,27};
yystate(26, Ics, Line, Tlen, _, _) ->
    {37,Tlen,Ics,Line};
yystate(25, [62|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 52, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {52,Tlen,Ics,Line,25};
yystate(24, [101|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 17, Tlen);
yystate(24, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,24};
yystate(23, [111|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 17, Tlen);
yystate(23, [97|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 17, Tlen);
yystate(23, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 110 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,23};
yystate(22, [62|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 40, Tlen);
yystate(22, [46|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 40, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(2, Ics, Line, Tlen+1, 40, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {40,Tlen,Ics,Line,22};
yystate(21, Ics, Line, Tlen, _, _) ->
    {47,Tlen,Ics,Line};
yystate(20, [110|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(20, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,20};
yystate(19, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 2, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 2, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 2, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,19};
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Tlen+1, 44, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {44,Tlen,Ics,Line,18};
yystate(17, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(17, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(17, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(17, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(17, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,17};
yystate(16, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 9, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 9, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 9, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,16};
yystate(15, [116|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 17, Tlen);
yystate(15, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,15};
yystate(14, Ics, Line, Tlen, _, _) ->
    {42,Tlen,Ics,Line};
yystate(13, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,13};
yystate(12, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,12};
yystate(11, [111|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,11};
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Tlen+1, 14, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,10};
yystate(9, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(8, [102|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 17, Tlen);
yystate(8, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,8};
yystate(7, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 0, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 0, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 0, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,7};
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(6, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,6};
yystate(5, [62|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 45, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {45,Tlen,Ics,Line,5};
yystate(4, [110|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,4};
yystate(3, [114|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,3};
yystate(2, [46|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 13, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(2, Ics, Line, Tlen+1, 13, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,2};
yystate(1, Ics, Line, Tlen, _, _) ->
    {46,Tlen,Ics,Line};
yystate(0, [95|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 7, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(12, Ics, Line, Tlen+1, 7, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(12, Ics, Line, Tlen+1, 7, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine);
yyaction(16, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars, TokenLine);
yyaction(17, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars, TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(19, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_19(TokenChars, TokenLine);
yyaction(20, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_20(TokenChars, TokenLine);
yyaction(21, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_21(TokenChars, TokenLine);
yyaction(22, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_22(TokenChars, TokenLine);
yyaction(23, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_23(TokenChars, TokenLine);
yyaction(24, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_24(TokenChars, TokenLine);
yyaction(25, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_25(TokenChars, TokenLine);
yyaction(26, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_26(TokenChars, TokenLine);
yyaction(27, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_27(TokenChars, TokenLine);
yyaction(28, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_28(TokenChars, TokenLine);
yyaction(29, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_29(TokenChars, TokenLine);
yyaction(30, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_30(TokenChars, TokenLine);
yyaction(31, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_31(TokenChars, TokenLine);
yyaction(32, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_32(TokenChars, TokenLine);
yyaction(33, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_33(TokenChars, TokenLine);
yyaction(34, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_34(TokenChars, TokenLine);
yyaction(35, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_35(TokenChars, TokenLine);
yyaction(36, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_36(TokenChars, TokenLine);
yyaction(37, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_37(TokenChars, TokenLine);
yyaction(38, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_38(TokenChars, TokenLine);
yyaction(39, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_39(TokenChars, TokenLine);
yyaction(40, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_40(TokenChars, TokenLine);
yyaction(41, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_41(TokenChars, TokenLine);
yyaction(42, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_42(TokenChars, TokenLine);
yyaction(43, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_43(TokenChars, TokenLine);
yyaction(44, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_44(TokenChars, TokenLine);
yyaction(45, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_45(TokenChars, TokenLine);
yyaction(46, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_46(TokenChars, TokenLine);
yyaction(47, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_47(TokenChars, TokenLine);
yyaction(48, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_48(TokenChars, TokenLine);
yyaction(49, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_49(TokenChars, TokenLine);
yyaction(50, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_50(TokenChars, TokenLine);
yyaction(51, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_51(TokenChars, TokenLine);
yyaction(52, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_52(TokenChars, TokenLine);
yyaction(53, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_53(TokenChars, TokenLine);
yyaction(54, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_54(TokenChars, TokenLine);
yyaction(55, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_55(TokenChars, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("./beehive_lexer.xrl", 3).
yyaction_0(TokenChars, TokenLine) ->
     { token, { 'or', TokenLine, TokenChars } } .

-compile({inline,yyaction_1/2}).
-file("./beehive_lexer.xrl", 4).
yyaction_1(TokenChars, TokenLine) ->
     { token, { 'and', TokenLine, TokenChars } } .

-compile({inline,yyaction_2/2}).
-file("./beehive_lexer.xrl", 5).
yyaction_2(TokenChars, TokenLine) ->
     { token, { 'not', TokenLine, TokenChars } } .

-compile({inline,yyaction_3/2}).
-file("./beehive_lexer.xrl", 7).
yyaction_3(TokenChars, TokenLine) ->
     { token, { bool, TokenLine, TokenChars } } .

-compile({inline,yyaction_4/2}).
-file("./beehive_lexer.xrl", 8).
yyaction_4(TokenChars, TokenLine) ->
     { token, { bool, TokenLine, TokenChars } } .

-compile({inline,yyaction_5/2}).
-file("./beehive_lexer.xrl", 10).
yyaction_5(TokenChars, TokenLine) ->
     { token, { mod, TokenLine, TokenChars } } .

-compile({inline,yyaction_6/2}).
-file("./beehive_lexer.xrl", 11).
yyaction_6(TokenChars, TokenLine) ->
     { token, { fn, TokenLine, TokenChars } } .

-compile({inline,yyaction_7/2}).
-file("./beehive_lexer.xrl", 12).
yyaction_7(TokenChars, TokenLine) ->
     { token, { pfn, TokenLine, TokenChars } } .

-compile({inline,yyaction_8/2}).
-file("./beehive_lexer.xrl", 14).
yyaction_8(TokenChars, TokenLine) ->
     { token, { 'if', TokenLine, TokenChars } } .

-compile({inline,yyaction_9/2}).
-file("./beehive_lexer.xrl", 15).
yyaction_9(TokenChars, TokenLine) ->
     { token, { then, TokenLine, TokenChars } } .

-compile({inline,yyaction_10/2}).
-file("./beehive_lexer.xrl", 16).
yyaction_10(TokenChars, TokenLine) ->
     { token, { else, TokenLine, TokenChars } } .

-compile({inline,yyaction_11/2}).
-file("./beehive_lexer.xrl", 17).
yyaction_11(TokenChars, TokenLine) ->
     { token, { match, TokenLine, TokenChars } } .

-compile({inline,yyaction_12/2}).
-file("./beehive_lexer.xrl", 18).
yyaction_12(TokenChars, TokenLine) ->
     { token, { to, TokenLine, TokenChars } } .

-compile({inline,yyaction_13/2}).
-file("./beehive_lexer.xrl", 20).
yyaction_13(TokenChars, TokenLine) ->
     { token, { int, TokenLine, TokenChars } } .

-compile({inline,yyaction_14/2}).
-file("./beehive_lexer.xrl", 21).
yyaction_14(TokenChars, TokenLine) ->
     { token, { float, TokenLine, TokenChars } } .

-compile({inline,yyaction_15/2}).
-file("./beehive_lexer.xrl", 22).
yyaction_15(TokenChars, TokenLine) ->
     { token, { atom, TokenLine, TokenChars } } .

-compile({inline,yyaction_16/2}).
-file("./beehive_lexer.xrl", 23).
yyaction_16(TokenChars, TokenLine) ->
     { token, { string, TokenLine, TokenChars } } .

-compile({inline,yyaction_17/2}).
-file("./beehive_lexer.xrl", 25).
yyaction_17(TokenChars, TokenLine) ->
     { token, { lowercase_word, TokenLine, TokenChars } } .

-compile({inline,yyaction_18/2}).
-file("./beehive_lexer.xrl", 26).
yyaction_18(TokenChars, TokenLine) ->
     { token, { capitalized_word, TokenLine, TokenChars } } .

-compile({inline,yyaction_19/2}).
-file("./beehive_lexer.xrl", 28).
yyaction_19(TokenChars, TokenLine) ->
     { token, { ')', TokenLine, TokenChars } } .

-compile({inline,yyaction_20/2}).
-file("./beehive_lexer.xrl", 29).
yyaction_20(TokenChars, TokenLine) ->
     { token, { '(', TokenLine, TokenChars } } .

-compile({inline,yyaction_21/2}).
-file("./beehive_lexer.xrl", 30).
yyaction_21(TokenChars, TokenLine) ->
     { token, { '}', TokenLine, TokenChars } } .

-compile({inline,yyaction_22/2}).
-file("./beehive_lexer.xrl", 31).
yyaction_22(TokenChars, TokenLine) ->
     { token, { '#{', TokenLine, TokenChars } } .

-compile({inline,yyaction_23/2}).
-file("./beehive_lexer.xrl", 32).
yyaction_23(TokenChars, TokenLine) ->
     { token, { ']', TokenLine, TokenChars } } .

-compile({inline,yyaction_24/2}).
-file("./beehive_lexer.xrl", 33).
yyaction_24(TokenChars, TokenLine) ->
     { token, { '[', TokenLine, TokenChars } } .

-compile({inline,yyaction_25/2}).
-file("./beehive_lexer.xrl", 34).
yyaction_25(TokenChars, TokenLine) ->
     { token, { '|~', TokenLine, TokenChars } } .

-compile({inline,yyaction_26/2}).
-file("./beehive_lexer.xrl", 35).
yyaction_26(TokenChars, TokenLine) ->
     { token, { '~|', TokenLine, TokenChars } } .

-compile({inline,yyaction_27/2}).
-file("./beehive_lexer.xrl", 36).
yyaction_27(TokenChars, TokenLine) ->
     { token, { '|~~', TokenLine, TokenChars } } .

-compile({inline,yyaction_28/2}).
-file("./beehive_lexer.xrl", 37).
yyaction_28(TokenChars, TokenLine) ->
     { token, { '~~|', TokenLine, TokenChars } } .

-compile({inline,yyaction_29/2}).
-file("./beehive_lexer.xrl", 38).
yyaction_29(TokenChars, TokenLine) ->
     { token, { '|', TokenLine, TokenChars } } .

-compile({inline,yyaction_30/2}).
-file("./beehive_lexer.xrl", 40).
yyaction_30(TokenChars, TokenLine) ->
     { token, { '!', TokenLine, TokenChars } } .

-compile({inline,yyaction_31/2}).
-file("./beehive_lexer.xrl", 41).
yyaction_31(TokenChars, TokenLine) ->
     { token, { '@', TokenLine, TokenChars } } .

-compile({inline,yyaction_32/2}).
-file("./beehive_lexer.xrl", 42).
yyaction_32(TokenChars, TokenLine) ->
     { token, { '#', TokenLine, TokenChars } } .

-compile({inline,yyaction_33/2}).
-file("./beehive_lexer.xrl", 43).
yyaction_33(TokenChars, TokenLine) ->
     { token, { '$', TokenLine, TokenChars } } .

-compile({inline,yyaction_34/2}).
-file("./beehive_lexer.xrl", 44).
yyaction_34(TokenChars, TokenLine) ->
     { token, { '%', TokenLine, TokenChars } } .

-compile({inline,yyaction_35/2}).
-file("./beehive_lexer.xrl", 45).
yyaction_35(TokenChars, TokenLine) ->
     { token, { '^', TokenLine, TokenChars } } .

-compile({inline,yyaction_36/2}).
-file("./beehive_lexer.xrl", 46).
yyaction_36(TokenChars, TokenLine) ->
     { token, { '&', TokenLine, TokenChars } } .

-compile({inline,yyaction_37/2}).
-file("./beehive_lexer.xrl", 48).
yyaction_37(TokenChars, TokenLine) ->
     { token, { '->', TokenLine, TokenChars } } .

-compile({inline,yyaction_38/2}).
-file("./beehive_lexer.xrl", 49).
yyaction_38(TokenChars, TokenLine) ->
     { token, { '|_|', TokenLine, TokenChars } } .

-compile({inline,yyaction_39/2}).
-file("./beehive_lexer.xrl", 51).
yyaction_39(TokenChars, TokenLine) ->
     { token, { '+', TokenLine, TokenChars } } .

-compile({inline,yyaction_40/2}).
-file("./beehive_lexer.xrl", 52).
yyaction_40(TokenChars, TokenLine) ->
     { token, { '-', TokenLine, TokenChars } } .

-compile({inline,yyaction_41/2}).
-file("./beehive_lexer.xrl", 53).
yyaction_41(TokenChars, TokenLine) ->
     { token, { '*', TokenLine, TokenChars } } .

-compile({inline,yyaction_42/2}).
-file("./beehive_lexer.xrl", 54).
yyaction_42(TokenChars, TokenLine) ->
     { token, { '/', TokenLine, TokenChars } } .

-compile({inline,yyaction_43/2}).
-file("./beehive_lexer.xrl", 56).
yyaction_43(TokenChars, TokenLine) ->
     { token, { ',', TokenLine, TokenChars } } .

-compile({inline,yyaction_44/2}).
-file("./beehive_lexer.xrl", 57).
yyaction_44(TokenChars, TokenLine) ->
     { token, { '.', TokenLine, TokenChars } } .

-compile({inline,yyaction_45/2}).
-file("./beehive_lexer.xrl", 58).
yyaction_45(TokenChars, TokenLine) ->
     { token, { ':', TokenLine, TokenChars } } .

-compile({inline,yyaction_46/2}).
-file("./beehive_lexer.xrl", 59).
yyaction_46(TokenChars, TokenLine) ->
     { token, { ':>', TokenLine, TokenChars } } .

-compile({inline,yyaction_47/2}).
-file("./beehive_lexer.xrl", 61).
yyaction_47(TokenChars, TokenLine) ->
     { token, { '<=>', TokenLine, TokenChars } } .

-compile({inline,yyaction_48/2}).
-file("./beehive_lexer.xrl", 62).
yyaction_48(TokenChars, TokenLine) ->
     { token, { '=>', TokenLine, TokenChars } } .

-compile({inline,yyaction_49/2}).
-file("./beehive_lexer.xrl", 64).
yyaction_49(TokenChars, TokenLine) ->
     { token, { '==', TokenLine, TokenChars } } .

-compile({inline,yyaction_50/2}).
-file("./beehive_lexer.xrl", 65).
yyaction_50(TokenChars, TokenLine) ->
     { token, { '!=', TokenLine, TokenChars } } .

-compile({inline,yyaction_51/2}).
-file("./beehive_lexer.xrl", 66).
yyaction_51(TokenChars, TokenLine) ->
     { token, { '>=', TokenLine, TokenChars } } .

-compile({inline,yyaction_52/2}).
-file("./beehive_lexer.xrl", 67).
yyaction_52(TokenChars, TokenLine) ->
     { token, { '<=', TokenLine, TokenChars } } .

-compile({inline,yyaction_53/2}).
-file("./beehive_lexer.xrl", 68).
yyaction_53(TokenChars, TokenLine) ->
     { token, { '>', TokenLine, TokenChars } } .

-compile({inline,yyaction_54/2}).
-file("./beehive_lexer.xrl", 69).
yyaction_54(TokenChars, TokenLine) ->
     { token, { '<', TokenLine, TokenChars } } .

-compile({inline,yyaction_55/2}).
-file("./beehive_lexer.xrl", 71).
yyaction_55(TokenChars, TokenLine) ->
     { token, { ws, TokenLine, TokenChars } } .

-file("c:/Program Files/Erlang OTP/lib/parsetools-2.4/include/leexinc.hrl", 313).
